version: '3'
services:
  nginx:                        # x
    # ---------------------
    # | Image / container |
    # ---------------------
    image: nginx:latest         # x
    container_name: my_nginx    # x
    # user: root
    # ipc: host
    # privileged: true
    environment:
      PYTHONIOENCODING: utf-8
      NGINX_HOST: localhost    # x
      NGINX_PORT: 80           # x
    # depends_on:
    #   - service_a
    #   - service_b
    
    # -----------
    # | Volumes |
    # -----------
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - ./html:/usr/share/nginx/html:ro         # x
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"   # USB webcam
    
    # -------------
    # | Execution |
    # -------------
    # depends_on:
    #   - postgres-server
    # init: true  # --init
    working_dir: /etc/nginx/    # x
    entrypoint: /bin/bash
    command: -c 'sleep 5 && sleep infinity'    # x
    restart: unless-stopped     # or "always", "no" (default)
    
    # -------------
    # | Resources |
    # -------------
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '512M'    # or '4g' (4GB)
        reservations:
          cpus: '0.5'
          memory: '256M'
          # devices:
          # - driver: nvidia
          #   device_ids: ['all'] # or ['0', '1']
          #   capabilities: [gpu]
    cpuset: "0,1"  # Restrict the service to CPUs 0 and 1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    
    # --------------
    # | Networking |
    # --------------
    ports:
      - "10080:80"
    # networks: # has two networks: "external-network-1" and "external-network-2"
    #   - external-network-2
    # extra_hosts:
    #   - "kafka:host-gateway"
    #   - "docker.com:141.193.213.21"

# networks:
#   default:
#     external:
#       name: external-network-1
#   external-network-2:
#     external: true
